# Generated by Django 6.0.7 on 2026-07-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('nazoratchi', 'Nazoratchi'), ('oquvchi', "O'quvchi")], default='admin', max_length=20),
        ),
    ]
