import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { CheckCircle2, Clock3, Medal, Sparkles, Trophy } from 'lucide-react';
import { boshlashUrinish, getMusobaqa, topshirishMusobaqa } from '../../api/competition';
import { Badge, Button, Card, ProgressBar, Skeleton } from '../../components/ui';
import { useLanguage } from '../../context/LanguageContext';
const formatTime=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
export default function MusobaqaTestPage(){
 const {id}=useParams();const navigate=useNavigate();const {t}=useLanguage();const [competition,setCompetition]=useState(null);const [session,setSession]=useState(null);const [answers,setAnswers]=useState({});const [remaining,setRemaining]=useState(0);const [countdown,setCountdown]=useState(null);const [result,setResult]=useState(null);const [loading,setLoading]=useState(true);const [starting,setStarting]=useState(false);const [submitting,setSubmitting]=useState(false);const autoSubmitted=useRef(false);
 const resume=useCallback(async()=>{const data=await boshlashUrinish(id);setSession(data);setRemaining(data.qolgan_soniya||0)},[id]);
 useEffect(()=>{getMusobaqa(id).then(async data=>{setCompetition(data);if(data.mening_urinishim?.status==='boshlandi')await resume();if(data.mening_urinishim?.status==='yakun')setResult(data.mening_urinishim)}).finally(()=>setLoading(false))},[id,resume]);
 const begin=async()=>{setStarting(true);for(const value of [3,2,1]){setCountdown(value);await new Promise(resolve=>setTimeout(resolve,850))}setCountdown(0);try{await resume()}finally{setStarting(false);setTimeout(()=>setCountdown(null),350)}};
 const payload=useMemo(()=>(session?.savollar||[]).map(q=>{const value=answers[q.id];if(q.tur==='text')return{savol:q.id,matn_javob:value||''};return{savol:q.id,tanlangan_javoblar:Array.isArray(value)?value:value?[value]:[]}}),[session,answers]);
 const submit=useCallback(async(automatic=false)=>{if(!session||submitting)return;if(!automatic&&!confirm('Javoblarni yakuniy topshirasizmi?'))return;setSubmitting(true);try{const data=await topshirishMusobaqa(id,payload);setResult(data);setSession(null)}finally{setSubmitting(false)}},[id,payload,session,submitting]);
 useEffect(()=>{if(!session||result)return;const timer=setInterval(()=>setRemaining(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer)},[session,result]);
 useEffect(()=>{if(session&&remaining===0&&!autoSubmitted.current){autoSubmitted.current=true;submit(true)}},[remaining,session,submit]);
 const choose=(q,answerId)=>setAnswers(current=>{if(q.tur==='multiple'){const prev=Array.isArray(current[q.id])?current[q.id]:[];return{...current,[q.id]:prev.includes(answerId)?prev.filter(v=>v!==answerId):[...prev,answerId]}}return{...current,[q.id]:answerId}});
 if(loading)return <Skeleton className="h-96 w-full"/>;if(!competition)return <Card className="p-8 text-center">Musobaqa topilmadi.</Card>;
 if(countdown!==null)return <div className="competition-countdown"><div className="competition-countdown__ring"><span>{countdown||'GO!'}</span></div><h2>{t('competition.countdown')}</h2><p>{competition.nomi}</p></div>;
 if(result)return <div className="competition-result animate-in"><div className="competition-result__icon"><Trophy size={44}/></div><span>{t('competition.result')}</span><h1>{result.foiz}%</h1><p>{t('competition.correct',{correct:result.togri_soni,total:result.jami_soni})}</p><div className="competition-result__ranking">{(result.reyting||competition.reyting||[]).slice(0,5).map(row=><div key={row.oquvchi_id}><Medal size={16}/><b>#{row.orin}</b><span>{row.ism}</span><strong>{row.foiz??row.ball}%</strong></div>)}</div><Button onClick={()=>navigate('/oquvchi/musobaqalar')}>Musobaqalarga qaytish</Button></div>;
 if(!session)return <div className="competition-ready animate-in"><div className="competition-ready__trophy"><Trophy size={40}/></div><Badge tone="warning">LIVE</Badge><h1>{competition.nomi}</h1><p>{competition.tavsif}</p><div className="competition-ready__meta"><span><Sparkles size={18}/>{t('competition.questions',{count:competition.savollar_soni})}</span><span><Clock3 size={18}/>{t('competition.minutes',{count:competition.davomiyligi_daq})}</span></div><h3>{t('competition.ready')}</h3><Button size="lg" loading={starting} onClick={begin}><Trophy size={19}/>{t('competition.enter')}</Button></div>;
 const answered=Object.keys(answers).filter(key=>Array.isArray(answers[key])?answers[key].length:Boolean(answers[key])).length;
 return <div className="competition-test animate-in"><div className="competition-test__sticky"><div><span>🏆 {competition.nomi}</span><strong>{answered}/{session.savollar.length} javob</strong></div><div className={`competition-test__timer ${remaining<60?'is-urgent':''}`}><Clock3 size={18}/>{formatTime(remaining)}</div><ProgressBar value={(answered/Math.max(session.savollar.length,1))*100}/></div><div className="space-y-4">{session.savollar.map((q,index)=><Card key={q.id} className="competition-question p-5"><div className="competition-question__number">{index+1}</div><h3>{q.matn}</h3>{q.rasm&&<img src={q.rasm} alt="" className="competition-question__image"/>}{q.tur==='text'?<input className="competition-question__text" value={answers[q.id]||''} onChange={e=>setAnswers(current=>({...current,[q.id]:e.target.value}))} placeholder="Javobni yozing"/>:<div className="competition-question__answers">{q.javoblar.map((a,aIndex)=>{const selected=q.tur==='multiple'?(answers[q.id]||[]).includes(a.id):answers[q.id]===a.id;return <button type="button" className={selected?'is-selected':''} key={a.id} onClick={()=>choose(q,a.id)}><span>{selected?<CheckCircle2 size={18}/>:String.fromCharCode(65+aIndex)}</span>{a.matn}</button>})}</div>}</Card>)}</div><Button className="competition-test__submit" size="lg" loading={submitting} onClick={()=>submit(false)}>{t('competition.submit')}</Button></div>;
}
