# Generated by Django 6.0.7 on 2026-07-20 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=500)),
                ('togri', models.BooleanField(default=False)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'db_table': 'javoblar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Mashq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(default='Mashq', max_length=200)),
                ('vaqt_chegarasi_daq', models.PositiveIntegerField(blank=True, null=True)),
                ('otish_bali_foiz', models.PositiveIntegerField(default=60)),
                ('dars', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mashq', to='courses.dars')),
            ],
            options={
                'verbose_name': 'Mashq',
                'verbose_name_plural': 'Mashqlar',
                'db_table': 'mashqlar',
            },
        ),
        migrations.CreateModel(
            name='MashqNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri_soni', models.PositiveIntegerField(default=0)),
                ('jami_soni', models.PositiveIntegerField(default=0)),
                ('foiz', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('urinish_raqami', models.PositiveIntegerField(default=1)),
                ('boshlangan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('tugagan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('mashq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='exams.mashq')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mashq natijasi',
                'verbose_name_plural': 'Mashq natijalari',
                'db_table': 'mashq_natijalari',
                'ordering': ['-boshlangan_vaqt'],
            },
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='savollar/rasm/')),
                ('tur', models.CharField(choices=[('single', "Bitta to'g'ri javob"), ('multiple', "Ko'p to'g'ri javob"), ('text', 'Matn kiritish')], default='single', max_length=20)),
                ('togri_matn_javob', models.CharField(blank=True, max_length=255)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('mashq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='exams.mashq')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'db_table': 'savollar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='OquvchiJavob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn_javob', models.TextField(blank=True)),
                ('togri_berilgan', models.BooleanField(default=False)),
                ('natija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berilgan_javoblar', to='exams.mashqnatija')),
                ('tanlangan_javoblar', models.ManyToManyField(blank=True, related_name='+', to='exams.javob')),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.savol')),
            ],
            options={
                'verbose_name': "O'quvchi javobi",
                'verbose_name_plural': "O'quvchi javoblari",
                'db_table': 'oquvchi_javoblari',
            },
        ),
        migrations.AddField(
            model_name='javob',
            name='savol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='exams.savol'),
        ),
    ]
