# Generated by Django 6.0.7 on 2026-07-20 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_daraja_ochish_uchun_foiz_oquvchifan_qolda_ochilgan'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('tavsif', models.CharField(blank=True, max_length=255)),
                ('narx_coin', models.PositiveIntegerField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('faol', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop mahsuloti',
                'verbose_name_plural': 'Shop mahsulotlari',
                'db_table': 'shop_mahsulotlari',
            },
        ),
        migrations.CreateModel(
            name='AdminAmalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amal', models.CharField(help_text="masalan: 'oquvchi_yaratildi', 'daraja_ochildi'", max_length=255)),
                ('tavsif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amal_loglari', to=settings.AUTH_USER_MODEL)),
                ('nishon_user', models.ForeignKey(blank=True, help_text="Amal kimga nisbatan bajarilgan (masalan qaysi o'quvchi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin amal logi',
                'verbose_name_plural': 'Admin amal loglari',
                'db_table': 'admin_amal_loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTarix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.IntegerField(help_text="Musbat — qo'shilgan, manfiy — sarflangan")),
                ('sabab', models.CharField(choices=[('mashq', 'Mashq yakunlandi'), ('gate_test', 'Gate Test topshirildi'), ('final_test', 'Final Test topshirildi'), ('shop', "Do'kondan xarid"), ('admin', "Admin tomonidan qo'lda berilgan")], max_length=20)),
                ('izoh', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tarixi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coin tarixi',
                'verbose_name_plural': 'Coin tarixi',
                'db_table': 'coin_tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(default='Yakuniy test', max_length=200)),
                ('otish_bali_foiz', models.PositiveIntegerField(default=70)),
                ('daraja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_test', to='courses.daraja')),
            ],
            options={
                'verbose_name': 'Final Test',
                'verbose_name_plural': 'Final Testlar',
                'db_table': 'final_testlar',
            },
        ),
        migrations.CreateModel(
            name='FinalTestSavol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('final_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='exams.finaltest')),
            ],
            options={
                'verbose_name': 'Final Test savoli',
                'verbose_name_plural': 'Final Test savollari',
                'db_table': 'final_test_savollari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='FinalTestJavob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=500)),
                ('togri', models.BooleanField(default=False)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='exams.finaltestsavol')),
            ],
            options={
                'verbose_name': 'Final Test javobi',
                'verbose_name_plural': 'Final Test javoblari',
                'db_table': 'final_test_javoblari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='GateTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(default='Daraja testi', max_length=200)),
                ('daraja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_test', to='courses.daraja')),
            ],
            options={
                'verbose_name': 'Gate Test',
                'verbose_name_plural': 'Gate Testlar',
                'db_table': 'gate_testlar',
            },
        ),
        migrations.CreateModel(
            name='GateTestNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri_soni', models.PositiveIntegerField(default=0)),
                ('jami_soni', models.PositiveIntegerField(default=0)),
                ('foiz', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('otdi', models.BooleanField(default=False)),
                ('urinish_raqami', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gate_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='exams.gatetest')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_test_natijalari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gate Test natijasi',
                'verbose_name_plural': 'Gate Test natijalari',
                'db_table': 'gate_test_natijalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GateTestSavol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('gate_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='exams.gatetest')),
            ],
            options={
                'verbose_name': 'Gate Test savoli',
                'verbose_name_plural': 'Gate Test savollari',
                'db_table': 'gate_test_savollari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='GateTestJavob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.CharField(max_length=500)),
                ('togri', models.BooleanField(default=False)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='javoblar', to='exams.gatetestsavol')),
            ],
            options={
                'verbose_name': 'Gate Test javobi',
                'verbose_name_plural': 'Gate Test javoblari',
                'db_table': 'gate_test_javoblari',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='OquvchiCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balans', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oquvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_balans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi coini",
                'verbose_name_plural': "O'quvchi coinlari",
                'db_table': 'oquvchi_coinlari',
            },
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(db_index=True, max_length=20, unique=True)),
                ('foiz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('berilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('daraja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikatlar', to='courses.daraja')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikatlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'db_table': 'sertifikatlar',
                'ordering': ['-berilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='FinalTestNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri_soni', models.PositiveIntegerField(default=0)),
                ('jami_soni', models.PositiveIntegerField(default=0)),
                ('foiz', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('otdi', models.BooleanField(default=False)),
                ('urinish_raqami', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='exams.finaltest')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_test_natijalari', to=settings.AUTH_USER_MODEL)),
                ('sertifikat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.sertifikat')),
            ],
            options={
                'verbose_name': 'Final Test natijasi',
                'verbose_name_plural': 'Final Test natijalari',
                'db_table': 'final_test_natijalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopBuyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx_coin', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_buyurtmalari', to=settings.AUTH_USER_MODEL)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyurtmalar', to='exams.shopmahsulot')),
            ],
            options={
                'verbose_name': 'Shop buyurtmasi',
                'verbose_name_plural': 'Shop buyurtmalari',
                'db_table': 'shop_buyurtmalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingTopshiriq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(help_text="O'quvchi talaffuz qilishi kerak bo'lgan matn/gap")),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_topshiriqlar', to='courses.dars')),
            ],
            options={
                'verbose_name': 'Speaking topshiriq',
                'verbose_name_plural': 'Speaking topshiriqlar',
                'db_table': 'speaking_topshiriqlar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_yozuv', models.FileField(blank=True, null=True, upload_to='speaking/')),
                ('ai_foiz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_izoh', models.TextField(blank=True)),
                ('baholanmoqda', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_natijalari', to=settings.AUTH_USER_MODEL)),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='exams.speakingtopshiriq')),
            ],
            options={
                'verbose_name': 'Speaking natijasi',
                'verbose_name_plural': 'Speaking natijalari',
                'db_table': 'speaking_natijalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingTopshiriq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(help_text="Topshiriq matni, masalan: 'Write 5 sentences about your daily routine.'")),
                ('minimal_soz_soni', models.PositiveIntegerField(default=30)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_topshiriqlar', to='courses.dars')),
            ],
            options={
                'verbose_name': 'Writing topshiriq',
                'verbose_name_plural': 'Writing topshiriqlar',
                'db_table': 'writing_topshiriqlar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='WritingNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn_javob', models.TextField()),
                ('ai_foiz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_izoh', models.TextField(blank=True, help_text='AI tomonidan berilgan qisqa fikr-mulohaza')),
                ('ai_xatolar', models.JSONField(blank=True, default=list, help_text="Aniqlangan grammatik xatolar ro'yxati")),
                ('baholanmoqda', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_natijalari', to=settings.AUTH_USER_MODEL)),
                ('topshiriq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='exams.writingtopshiriq')),
            ],
            options={
                'verbose_name': 'Writing natijasi',
                'verbose_name_plural': 'Writing natijalari',
                'db_table': 'writing_natijalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
