# Generated by Django 5.1.6 on 2026-07-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_shopbuyurtma_status_soz_oyini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointarix',
            name='sabab',
            field=models.CharField(choices=[('mashq', 'Mashq yakunlandi'), ('gate_test', 'Gate Test topshirildi'), ('final_test', 'Final Test topshirildi'), ('shop', "Do'kondan xarid"), ('soz_oyini', "So'z o'yini"), ('admin', "Admin tomonidan qo'lda berilgan")], max_length=20),
        ),
    ]
