# Generated for Al-Aziz platform feature expansion.
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_user_token_version_kirishtarixi'),
        ('courses', '0002_daraja_ochish_uchun_foiz_oquvchifan_qolda_ochilgan'),
        ('exams', '0006_ai_murojaat_platform_sozlama'),
    ]

    operations = [
        migrations.AddField(model_name='gatetest', name='vaqt_chegarasi_daq', field=models.PositiveIntegerField(default=25)),
        migrations.AddField(model_name='finaltest', name='vaqt_chegarasi_daq', field=models.PositiveIntegerField(default=30)),
        migrations.AddField(model_name='sertifikat', name='faol', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='sertifikat', name='bekor_qilingan_sana', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='sertifikat', name='bekor_sabab', field=models.CharField(blank=True, max_length=255)),
        migrations.AddField(model_name='platformsozlama', name='tezkor_oyin_har_javob_coin', field=models.PositiveIntegerField(default=1)),
        migrations.AddField(model_name='platformsozlama', name='tezkor_oyin_mukammal_bonus', field=models.PositiveIntegerField(default=5)),
        migrations.AddField(model_name='platformsozlama', name='birinchi_urinish_bonus', field=models.PositiveIntegerField(default=3)),
        migrations.AddField(model_name='platformsozlama', name='mukammal_test_bonus', field=models.PositiveIntegerField(default=10)),
        migrations.AddField(model_name='platformsozlama', name='bildirishnomalar_faol', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='platformsozlama', name='tolov_nazorati_faol', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='platformsozlama', name='tolov_ogohlantirish_kun', field=models.PositiveIntegerField(default=3)),
        migrations.AlterField(
            model_name='cointarix', name='sabab',
            field=models.CharField(choices=[('mashq','Mashq yakunlandi'),('gate_test','Gate Test topshirildi'),('final_test','Final Test topshirildi'),('shop',"Do'kondan xarid"),('tezkor_oyin',"Tezkor tarjima o'yini"),('yutuq','Yutuq mukofoti'),('kunlik','Kunlik faollik'),('admin',"Admin tomonidan qo'lda berilgan")], max_length=20),
        ),
        migrations.DeleteModel(name='SozOyiniSessiya'),
        migrations.CreateModel(
            name='Bildirishnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=180)),
                ('matn', models.TextField()),
                ('tur', models.CharField(choices=[('info','Ma’lumot'),('success','Muvaffaqiyat'),('warning','Ogohlantirish'),('danger','Muhim')], default='info', max_length=20)),
                ('target_turi', models.CharField(choices=[('all','Barcha o‘quvchilar'),('user','Bitta o‘quvchi'),('fan','Fan bo‘yicha'),('daraja','Daraja bo‘yicha')], default='all', max_length=20)),
                ('havola', models.CharField(blank=True, max_length=300)),
                ('faol', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tugash_sana', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yaratgan_bildirishnomalar', to='accounts.user')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shaxsiy_bildirishnomalar', to='accounts.user')),
                ('target_fan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalar', to='courses.fan')),
                ('target_daraja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalar', to='courses.daraja')),
            ],
            options={'db_table':'bildirishnomalar','ordering':['-created_at']},
        ),
        migrations.AddIndex(model_name='bildirishnoma', index=models.Index(fields=['faol','-created_at'], name='bildirishnoma_faol_idx')),
        migrations.CreateModel(
            name='BildirishnomaOqildi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oqilgan_at', models.DateTimeField(auto_now_add=True)),
                ('bildirishnoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oqilganlar', to='exams.bildirishnoma')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oqilgan_bildirishnomalar', to='accounts.user')),
            ],
            options={'db_table':'bildirishnoma_oqildi','unique_together':{('bildirishnoma','oquvchi')}},
        ),
        migrations.CreateModel(
            name='PlacementNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri_soni', models.PositiveIntegerField(default=0)),
                ('jami_soni', models.PositiveIntegerField(default=0)),
                ('foiz', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('javoblar', models.JSONField(blank=True, default=list)),
                ('xavfsizlik', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_natijalari', to='courses.fan')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_natijalari', to='accounts.user')),
                ('tavsiya_daraja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_tavsiyalari', to='courses.daraja')),
            ],
            options={'db_table':'placement_natijalari','ordering':['-created_at']},
        ),
        migrations.AddField(model_name='placementnatija', name='tasdiqlangan', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='placementnatija', name='tasdiqlangan_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='placementnatija', name='tasdiqlagan', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasdiqlagan_placement_natijalari', to='accounts.user')),
        migrations.CreateModel(
            name='TestXavfsizlikLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_turi', models.CharField(choices=[('mashq','Mashq'),('gate','Gate Test'),('final','Final Test'),('placement','Placement Test')], max_length=20)),
                ('obyekt_id', models.PositiveIntegerField(default=0)),
                ('davomiylik_soniya', models.PositiveIntegerField(default=0)),
                ('sahifadan_chiqish_soni', models.PositiveIntegerField(default=0)),
                ('shubhali', models.BooleanField(default=False)),
                ('sabablar', models.JSONField(blank=True, default=list)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_manzil', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_xavfsizlik_loglari', to='accounts.user')),
            ],
            options={'db_table':'test_xavfsizlik_loglari','ordering':['-created_at']},
        ),
        migrations.AddIndex(model_name='testxavfsizliklog', index=models.Index(fields=['shubhali','-created_at'], name='test_xavfsiz_shubha_idx')),
        migrations.CreateModel(
            name='FaoliyatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amal', models.CharField(max_length=60)),
                ('tavsif', models.CharField(blank=True, max_length=300)),
                ('obyekt_turi', models.CharField(blank=True, max_length=60)),
                ('obyekt_id', models.PositiveIntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ip_manzil', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faoliyat_loglari', to='accounts.user')),
            ],
            options={'db_table':'foydalanuvchi_faoliyati','ordering':['-created_at']},
        ),
        migrations.AddIndex(model_name='faoliyatlog', index=models.Index(fields=['user','-created_at'], name='faoliyat_user_created_idx')),
        migrations.CreateModel(
            name='OquvchiKunlikFaollik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunlik_faollik', to='accounts.user')),
            ],
            options={'db_table':'oquvchi_kunlik_faollik','ordering':['-sana'],'unique_together':{('oquvchi','sana')}},
        ),
        migrations.CreateModel(
            name='Yutuq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('nomi', models.CharField(max_length=150)),
                ('tavsif', models.CharField(max_length=300)),
                ('icon', models.CharField(default='🏆', max_length=40)),
                ('coin_mukofot', models.PositiveIntegerField(default=0)),
                ('faol', models.BooleanField(default=True)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={'db_table':'yutuqlar','ordering':['tartib','id']},
        ),
        migrations.CreateModel(
            name='OquvchiYutuq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('olingan_at', models.DateTimeField(auto_now_add=True)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yutuqlari', to='accounts.user')),
                ('yutuq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olganlar', to='exams.yutuq')),
            ],
            options={'db_table':'oquvchi_yutuqlari','ordering':['-olingan_at'],'unique_together':{('oquvchi','yutuq')}},
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tolangan_summa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chegirma_foiz', models.PositiveIntegerField(default=0)),
                ('boshlanish_sana', models.DateField()),
                ('tugash_sana', models.DateField()),
                ('status', models.CharField(choices=[('tolangan','To‘langan'),('qisman','Qisman to‘langan'),('qarzdor','Qarzdor'),('imtiyozli','Imtiyozli'),('bekor','Bekor qilingan')], default='qarzdor', max_length=20)),
                ('izoh', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiritgan_tolovlar', to='accounts.user')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='accounts.user')),
            ],
            options={'db_table':'tolovlar','ordering':['-tugash_sana','-created_at']},
        ),
        migrations.AddIndex(model_name='tolov', index=models.Index(fields=['oquvchi','-tugash_sana'], name='tolov_user_end_idx')),
        migrations.CreateModel(
            name='TezkorOyiniSessiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('savollar', models.JSONField(default=list)),
                ('togri_soni', models.PositiveIntegerField(default=0)),
                ('jami_soni', models.PositiveIntegerField(default=10)),
                ('berilgan_coin', models.PositiveIntegerField(default=0)),
                ('tugallangan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tezkor_oyin_sessiyalari', to='courses.fan')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tezkor_oyin_sessiyalari', to='accounts.user')),
            ],
            options={'db_table':'tezkor_oyin_sessiyalari','ordering':['-created_at']},
        ),
    ]
