# Generated by Django 6.0.7 on 2026-07-20 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True)),
                ('tavsif', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('tartib', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'fanlar',
                'ordering': ['tartib', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Daraja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darajalar', to='courses.fan')),
            ],
            options={
                'verbose_name': 'Daraja',
                'verbose_name_plural': 'Darajalar',
                'db_table': 'darajalar',
                'ordering': ['tartib'],
                'unique_together': {('fan', 'nomi')},
            },
        ),
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('daraja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzular', to='courses.daraja')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'db_table': 'mavzular',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('tushuntirish_matn', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='darslar/video/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='darslar/audio/')),
                ('misollar', models.TextField(blank=True)),
                ('tartib', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darslar', to='courses.mavzu')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'db_table': 'darslar',
                'ordering': ['tartib'],
            },
        ),
        migrations.CreateModel(
            name='DarsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_tugatilgan', models.BooleanField(default=False)),
                ('video_pozitsiya_soniya', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresslar', to='courses.dars')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dars_progresslari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dars progressi',
                'verbose_name_plural': 'Dars progresslari',
                'db_table': 'dars_progress',
                'unique_together': {('oquvchi', 'dars')},
            },
        ),
        migrations.CreateModel(
            name='OquvchiFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biriktirgan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biriktirishlar', to=settings.AUTH_USER_MODEL)),
                ('daraja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biriktirilgan_oquvchilar', to='courses.daraja')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biriktirilgan_fanlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi fani",
                'verbose_name_plural': "O'quvchi fanlari",
                'db_table': 'oquvchi_fanlari',
                'unique_together': {('oquvchi', 'daraja')},
            },
        ),
    ]
