# Generated by Django 6.0.7 on 2026-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daraja',
            name='ochish_uchun_foiz',
            field=models.PositiveIntegerField(default=60, help_text="Gate Test'dan o'tish uchun kerakli minimal foiz"),
        ),
        migrations.AddField(
            model_name='oquvchifan',
            name='qolda_ochilgan',
            field=models.BooleanField(default=True),
        ),
    ]
