import { useState } from 'react';
import { DatabaseBackup, Download, RotateCcw, TriangleAlert, Upload } from 'lucide-react';
import { downloadBackup, restoreBackup } from '../../api/features';
import { Button, Card, Input } from '../../components/ui';
import { useToast } from '../../context/ToastContext';

export default function BackupPage() {
  const { showToast } = useToast(); const [file, setFile] = useState(null); const [confirmText, setConfirmText] = useState(''); const [busy, setBusy] = useState(false);
  const download = async () => { setBusy(true); try { await downloadBackup(); showToast('Backup yuklab olindi.'); } catch (e) { showToast(e.response?.data?.detail || 'Backup olinmadi.', 'danger'); } finally { setBusy(false); } };
  const restore = async (e) => { e.preventDefault(); if (!file) return showToast('JSON backup faylini tanlang.', 'danger'); if (!confirm('Backup tiklansa mavjud ma’lumotlar o‘zgarishi mumkin. Davom etasizmi?')) return; setBusy(true); try { const r = await restoreBackup(file, confirmText); showToast(r.detail || 'Backup tiklandi.'); setFile(null); setConfirmText(''); } catch (err) { showToast(err.response?.data?.detail || 'Tiklashda xato.', 'danger'); } finally { setBusy(false); } };
  return <div className="animate-in space-y-5"><div><h1 className="font-display text-2xl font-extrabold">Backup va tiklash</h1><p className="text-sm mt-1" style={{ color: '#8A8371' }}>Platforma ma’lumotlarini saqlang va zaruratda qayta tiklang.</p></div><div className="grid lg:grid-cols-2 gap-5"><Card className="p-6"><div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{ background: '#E4EFE6' }}><DatabaseBackup size={23} /></div><h2 className="font-display text-xl font-bold mt-4">Yangi backup olish</h2><p className="text-sm mt-2" style={{ color: '#8A8371' }}>O‘quvchilar, natijalar, kurslar, sertifikatlar, to‘lovlar va sozlamalar ZIP ichidagi JSON faylga saqlanadi.</p><Button className="mt-5" onClick={download} loading={busy}><Download size={17} /> ZIP backup yuklash</Button></Card><Card className="p-6"><div className="flex items-start gap-3 p-4 rounded-xl" style={{ background: '#FFF4E4' }}><TriangleAlert size={20} style={{ color: '#A96600' }} /><p className="text-sm" style={{ color: '#7A541D' }}>Tiklashdan oldin albatta hozirgi bazaning yangi backup nusxasini oling. Faqat ZIP ichidan chiqarilgan <strong>.json</strong> fayl qabul qilinadi.</p></div><form onSubmit={restore} className="space-y-4 mt-5"><label className="block"><span className="block text-sm font-medium mb-1.5">JSON backup fayli</span><input type="file" accept="application/json,.json" onChange={e => setFile(e.target.files?.[0] || null)} className="w-full p-3 rounded-xl border text-sm" style={{ borderColor: 'var(--color-line)' }} /></label><Input label="Tasdiqlash" hint="Aniq TIKLASH deb yozing." value={confirmText} onChange={e => setConfirmText(e.target.value)} placeholder="TIKLASH" /><Button type="submit" variant="danger" loading={busy} disabled={confirmText !== 'TIKLASH'}><RotateCcw size={17} /> Backupni tiklash</Button></form></Card></div></div>;
}
