import { useEffect, useState } from 'react';
import { createMusobaqa, getMusobaqalar, yakunlaMusobaqa } from '../../api/adminExtra';
import { getFanlar, getFiliallar } from '../../api/admin';
import { Badge, Button, Card, Input, Modal, Select } from '../../components/ui';
import { Trophy, Plus, Medal } from 'lucide-react';

const empty = { nomi:'', tavsif:'', boshlanish_sana:'', tugash_sana:'', fan:'', filial:'', status:'faol', birinchi_coin:100, ikkinchi_coin:60, uchinchi_coin:30 };
export default function MusobaqalarPage(){
  const [items,setItems]=useState([]); const [fanlar,setFanlar]=useState([]); const [filiallar,setFiliallar]=useState([]); const [open,setOpen]=useState(false); const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false);
  const load=()=>Promise.all([getMusobaqalar(),getFanlar(),getFiliallar()]).then(([a,b,c])=>{setItems(a.results||a);setFanlar(b.results||b);setFiliallar(c.results||c)});
  useEffect(()=>{load()},[]);
  const submit=async e=>{e.preventDefault();setSaving(true);try{await createMusobaqa({...form,fan:form.fan||null,filial:form.filial||null,birinchi_coin:Number(form.birinchi_coin),ikkinchi_coin:Number(form.ikkinchi_coin),uchinchi_coin:Number(form.uchinchi_coin)});setOpen(false);setForm(empty);load()}finally{setSaving(false)}};
  const finish=async id=>{if(!confirm('Musobaqani yakunlab, 1–3 o‘rinlarga coin berilsinmi?'))return;await yakunlaMusobaqa(id);load()};
  return <div className="animate-in"><div className="flex items-center justify-between gap-3 mb-6"><div><h1 className="font-display text-2xl font-bold">Reyting va musobaqalar</h1><p className="text-sm" style={{color:'var(--color-muted)'}}>Haftalik yoki oylik bellashuvlar yarating.</p></div><Button onClick={()=>setOpen(true)}><Plus size={16}/>Yangi musobaqa</Button></div>
  <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{items.map(item=><Card key={item.id} className="p-5"><div className="flex justify-between gap-3"><div><div className="flex items-center gap-2"><Trophy size={18} style={{color:'var(--color-olive)'}}/><h2 className="font-display font-bold">{item.nomi}</h2></div><p className="text-xs mt-1" style={{color:'var(--color-muted)'}}>{item.boshlanish_sana} — {item.tugash_sana}</p></div><Badge tone={item.status==='yakun'?'success':'warning'}>{item.status}</Badge></div><p className="text-sm mt-3">{item.tavsif}</p><div className="mt-4 space-y-2">{(item.reyting||[]).slice(0,5).map(r=><div key={r.oquvchi_id} className="flex items-center gap-2 p-2 rounded-xl" style={{background:'var(--color-paper-warm)'}}><Medal size={15}/><span className="w-7">#{r.orin}</span><span className="flex-1 truncate">{r.ism}</span><b>{r.ball}</b></div>)}</div>{item.status!=='yakun'&&<Button className="mt-4" variant="secondary" onClick={()=>finish(item.id)}>Yakunlash va coin berish</Button>}</Card>)}</div>
  <Modal open={open} onClose={()=>setOpen(false)} title="Yangi musobaqa"><form onSubmit={submit} className="space-y-3"><Input label="Nomi" required value={form.nomi} onChange={e=>setForm({...form,nomi:e.target.value})}/><Input label="Tavsif" value={form.tavsif} onChange={e=>setForm({...form,tavsif:e.target.value})}/><div className="grid grid-cols-2 gap-3"><Input type="date" label="Boshlanish" required value={form.boshlanish_sana} onChange={e=>setForm({...form,boshlanish_sana:e.target.value})}/><Input type="date" label="Tugash" required value={form.tugash_sana} onChange={e=>setForm({...form,tugash_sana:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><Select label="Fan" value={form.fan} onChange={e=>setForm({...form,fan:e.target.value})}><option value="">Barcha fanlar</option>{fanlar.map(f=><option key={f.id} value={f.id}>{f.nomi}</option>)}</Select><Select label="Filial" value={form.filial} onChange={e=>setForm({...form,filial:e.target.value})}><option value="">Barcha filiallar</option>{filiallar.map(f=><option key={f.id} value={f.id}>{f.nomi}</option>)}</Select></div><div className="grid grid-cols-3 gap-2"><Input type="number" label="1-o‘rin" value={form.birinchi_coin} onChange={e=>setForm({...form,birinchi_coin:e.target.value})}/><Input type="number" label="2-o‘rin" value={form.ikkinchi_coin} onChange={e=>setForm({...form,ikkinchi_coin:e.target.value})}/><Input type="number" label="3-o‘rin" value={form.uchinchi_coin} onChange={e=>setForm({...form,uchinchi_coin:e.target.value})}/></div><Button type="submit" loading={saving} className="w-full">Saqlash</Button></form></Modal></div>
}
