import { useEffect, useMemo, useState } from 'react';
import { BrainCircuit, CheckCircle2, Search } from 'lucide-react';
import { confirmPlacementNatija, getPlacementNatijalar } from '../../api/features';
import { Badge, Button, Card, EmptyState, Skeleton } from '../../components/ui';
import { useToast } from '../../context/ToastContext';

export default function PlacementNatijalarPage() {
  const { showToast } = useToast();
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [q, setQ] = useState(''); const [busy, setBusy] = useState(null);
  const load = () => { setLoading(true); getPlacementNatijalar().then(setItems).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => { const s = q.toLowerCase().trim(); return s ? items.filter(x => `${x.oquvchi_ism} ${x.username} ${x.fan} ${x.tavsiya_daraja}`.toLowerCase().includes(s)) : items; }, [items, q]);
  const confirmLevel = async item => { if (!confirm(`${item.oquvchi_ism}ga ${item.tavsiya_daraja} darajasini biriktirasizmi?`)) return; setBusy(item.id); try { const result = await confirmPlacementNatija(item.id); showToast(result.detail || 'Daraja biriktirildi.'); load(); } catch (e) { showToast(e.response?.data?.detail || 'Daraja biriktirilmadi.', 'danger'); } finally { setBusy(null); } };
  return <div className="animate-in space-y-5"><div><h1 className="font-display text-2xl font-extrabold">Placement Test natijalari</h1><p className="text-sm mt-1" style={{ color: '#8A8371' }}>Natijani ko‘rib, tavsiya qilingan darajani o‘quvchiga tasdiqlang.</p></div><div className="relative max-w-lg"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2" /><input className="search-input" style={{ paddingLeft: 40 }} value={q} onChange={e => setQ(e.target.value)} placeholder="O‘quvchi, fan yoki daraja..." /></div>{loading ? <Skeleton className="h-64" /> : !filtered.length ? <Card><EmptyState icon={BrainCircuit} title="Natija yo‘q" description="O‘quvchilar placement test topshirganda shu yerda ko‘rinadi." /></Card> : <Card className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b" style={{ borderColor: 'var(--color-line)', color: '#8A8371' }}><th className="p-4">O‘quvchi</th><th className="p-4">Fan</th><th className="p-4">Natija</th><th className="p-4">Tavsiya</th><th className="p-4">Holat</th><th className="p-4">Sana</th></tr></thead><tbody>{filtered.map(x => <tr key={x.id} className="border-b last:border-0" style={{ borderColor: 'var(--color-line)' }}><td className="p-4"><p className="font-semibold">{x.oquvchi_ism}</p><p className="text-xs" style={{ color: '#8A8371' }}>{x.username}</p></td><td className="p-4">{x.fan}</td><td className="p-4"><Badge tone={Number(x.foiz) >= 80 ? 'success' : Number(x.foiz) >= 50 ? 'warning' : 'danger'}>{Number(x.foiz).toFixed(0)}%</Badge></td><td className="p-4 font-semibold">{x.tavsiya_daraja || '—'}</td><td className="p-4">{x.tasdiqlangan ? <Badge tone="success"><CheckCircle2 size={12} className="mr-1" /> Tasdiqlangan</Badge> : <Button size="sm" onClick={() => confirmLevel(x)} loading={busy === x.id} disabled={!x.tavsiya_daraja_id}>Darajani tasdiqlash</Button>}</td><td className="p-4 whitespace-nowrap">{new Date(x.created_at).toLocaleString('uz-UZ')}</td></tr>)}</tbody></table></Card>}</div>;
}
