import { useEffect, useState } from 'react';
import { ShieldAlert, ShieldCheck } from 'lucide-react';
import { getTestXavfsizligi } from '../../api/features';
import { Badge, Button, Card, EmptyState, Skeleton, StatCard } from '../../components/ui';

export default function TestXavfsizligiPage() {
  const [data, setData] = useState(null); const [only, setOnly] = useState(false); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); getTestXavfsizligi(only).then(setData).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [only]);
  return <div className="animate-in space-y-5"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h1 className="font-display text-2xl font-extrabold">Test xavfsizligi</h1><p className="text-sm mt-1" style={{ color: '#8A8371' }}>Test vaqti, sahifadan chiqish va shubhali urinishlarni kuzating.</p></div><Button variant={only ? 'primary' : 'secondary'} onClick={() => setOnly(!only)}><ShieldAlert size={17} /> Faqat shubhali</Button></div>{data && <div className="grid sm:grid-cols-2 gap-4"><StatCard label="Jami urinish" value={data.jami} icon={ShieldCheck} /><StatCard label="Shubhali urinish" value={data.shubhali_soni} icon={ShieldAlert} accent="amber" /></div>}{loading ? <Skeleton className="h-72" /> : !data?.natijalar?.length ? <Card><EmptyState icon={ShieldCheck} title="Log topilmadi" description="Testlar topshirilganda xavfsizlik loglari paydo bo‘ladi." /></Card> : <div className="space-y-3">{data.natijalar.map(x => <Card key={x.id} className="p-5" style={{ borderColor: x.shubhali ? '#E8B6AE' : 'var(--color-line)' }}><div className="flex flex-col sm:flex-row gap-3 justify-between"><div><div className="flex flex-wrap gap-2 items-center"><p className="font-semibold">{x.oquvchi_ism}</p><Badge tone="forest">{x.test_turi}</Badge><Badge tone={x.shubhali ? 'danger' : 'success'}>{x.shubhali ? 'Shubhali' : 'Oddiy'}</Badge></div><p className="text-sm mt-2" style={{ color: '#6F695C' }}>Davomiylik: {Math.floor(x.davomiylik_soniya / 60)} daq {x.davomiylik_soniya % 60} soniya · Sahifadan chiqish: {x.sahifadan_chiqish_soni}</p>{x.sabablar?.length > 0 && <p className="text-sm mt-2 font-semibold" style={{ color: 'var(--color-red)' }}>Sabab: {x.sabablar.join(', ')}</p>}<p className="text-xs mt-2" style={{ color: '#9C9584' }}>Login: {x.username} · IP: {x.ip_manzil || '—'}</p></div><p className="text-xs whitespace-nowrap" style={{ color: '#8A8371' }}>{new Date(x.created_at).toLocaleString('uz-UZ')}</p></div></Card>)}</div>}</div>;
}
