import { useEffect, useMemo, useState } from 'react';
import { CreditCard, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { createTolov, deleteTolov, getAdminTolovlar, updateTolov } from '../../api/features';
import { getAdminOquvchilar } from '../../api/admin';
import { Badge, Button, Card, EmptyState, Input, Modal, Select, Skeleton, Textarea } from '../../components/ui';
import { useToast } from '../../context/ToastContext';

const today = () => new Date().toISOString().slice(0, 10);
const plusMonth = () => { const d = new Date(); d.setMonth(d.getMonth() + 1); return d.toISOString().slice(0, 10); };
const emptyForm = { oquvchi: '', summa: 0, tolangan_summa: 0, chegirma_foiz: 0, boshlanish_sana: today(), tugash_sana: plusMonth(), status: 'qarzdor', izoh: '' };
const statusTone = { tolangan: 'success', qisman: 'warning', qarzdor: 'danger', imtiyozli: 'forest', bekor: 'neutral' };

export default function TolovlarPage() {
  const { showToast } = useToast();
  const [items, setItems] = useState([]); const [students, setStudents] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [query, setQuery] = useState(''); const [modal, setModal] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(emptyForm);
  const load = async () => { setLoading(true); try { const [p, s] = await Promise.all([getAdminTolovlar(), getAdminOquvchilar()]); setItems(p); setStudents(s.results || s); } catch (e) { showToast(e.response?.data?.detail || 'To‘lovlar yuklanmadi.', 'danger'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? items.filter(x => `${x.oquvchi_ism} ${x.username} ${x.filial_nomi} ${x.status_display}`.toLowerCase().includes(q)) : items; }, [items, query]);
  const openCreate = () => { setEditing(null); setForm(emptyForm); setModal(true); };
  const openEdit = x => { setEditing(x); setForm({ oquvchi: x.oquvchi, summa: Number(x.summa), tolangan_summa: Number(x.tolangan_summa), chegirma_foiz: x.chegirma_foiz, boshlanish_sana: x.boshlanish_sana, tugash_sana: x.tugash_sana, status: x.status, izoh: x.izoh || '' }); setModal(true); };
  const submit = async e => { e.preventDefault(); setSaving(true); try { if (editing) await updateTolov(editing.id, form); else await createTolov(form); showToast(editing ? 'To‘lov yangilandi.' : 'To‘lov kiritildi.'); setModal(false); load(); } catch (err) { showToast(err.response?.data?.detail || 'To‘lov saqlanmadi.', 'danger'); } finally { setSaving(false); } };
  const remove = async x => { if (!confirm(`${x.oquvchi_ism} to‘lov yozuvini o‘chirasizmi?`)) return; try { await deleteTolov(x.id); showToast('To‘lov o‘chirildi.'); load(); } catch { showToast('O‘chirishda xato.', 'danger'); } };
  const money = v => `${Number(v || 0).toLocaleString('uz-UZ')} so‘m`;
  return <div className="animate-in space-y-5"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h1 className="font-display text-2xl font-extrabold">To‘lov va foydalanish muddati</h1><p className="text-sm mt-1" style={{ color: '#8A8371' }}>O‘quvchi to‘lovi, qarzdorligi va platformadan foydalanish muddatini boshqaring.</p></div><Button onClick={openCreate}><Plus size={17} /> To‘lov kiritish</Button></div><div className="relative max-w-lg"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2" /><input className="search-input" style={{ paddingLeft: 40 }} value={query} onChange={e => setQuery(e.target.value)} placeholder="O‘quvchi, login yoki filial..." /></div>{loading ? <div className="space-y-3"><Skeleton className="h-28" /><Skeleton className="h-28" /></div> : !filtered.length ? <Card><EmptyState icon={CreditCard} title="To‘lov yozuvi yo‘q" description="Birinchi o‘quvchi uchun to‘lov va muddat kiriting." /></Card> : <div className="grid xl:grid-cols-2 gap-4">{filtered.map(x => <Card key={x.id} className="p-5"><div className="flex justify-between gap-3"><div><div className="flex flex-wrap gap-2 items-center"><h2 className="font-display font-bold">{x.oquvchi_ism}</h2><Badge tone={statusTone[x.status] || 'neutral'}>{x.status_display}</Badge></div><p className="text-xs mt-1" style={{ color: '#8A8371' }}>{x.username}{x.filial_nomi ? ` · ${x.filial_nomi}` : ''}</p></div><div className="flex gap-1"><button className="p-2 rounded-lg hover:bg-black/5" onClick={() => openEdit(x)} title="Tahrirlash"><Pencil size={16} /></button><button className="p-2 rounded-lg hover:bg-red-50" onClick={() => remove(x)} title="O‘chirish"><Trash2 size={16} style={{ color: 'var(--color-red)' }} /></button></div></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mt-4"><div><p className="text-xs" style={{ color: '#8A8371' }}>Jami</p><p className="font-semibold text-sm mt-1">{money(x.summa)}</p></div><div><p className="text-xs" style={{ color: '#8A8371' }}>To‘langan</p><p className="font-semibold text-sm mt-1">{money(x.tolangan_summa)}</p></div><div><p className="text-xs" style={{ color: '#8A8371' }}>Qoldiq</p><p className="font-semibold text-sm mt-1" style={{ color: Number(x.qolgan_summa) > 0 ? 'var(--color-red)' : 'var(--color-forest)' }}>{money(x.qolgan_summa)}</p></div></div><div className="mt-4 pt-4 border-t text-sm" style={{ borderColor: 'var(--color-line)', color: '#6F695C' }}><p>{x.boshlanish_sana} — {x.tugash_sana}</p>{x.chegirma_foiz > 0 && <p className="mt-1">Chegirma: {x.chegirma_foiz}%</p>}{x.izoh && <p className="mt-1">{x.izoh}</p>}</div></Card>)}</div>}
  <Modal open={modal} onClose={() => setModal(false)} title={editing ? 'To‘lovni tahrirlash' : 'Yangi to‘lov'} wide><form onSubmit={submit} className="space-y-4">{!editing && <Select label="O‘quvchi" required value={form.oquvchi} onChange={e => setForm({ ...form, oquvchi: e.target.value })}><option value="">Tanlang</option>{students.map(x => <option key={x.id} value={x.id}>{x.ism} {x.familya} ({x.username})</option>)}</Select>}<div className="grid sm:grid-cols-2 gap-3"><Input type="number" min="0" label="Jami summa" value={form.summa} onChange={e => setForm({ ...form, summa: Number(e.target.value) })} /><Input type="number" min="0" label="To‘langan summa" value={form.tolangan_summa} onChange={e => setForm({ ...form, tolangan_summa: Number(e.target.value) })} /><Input type="number" min="0" max="100" label="Chegirma (%)" value={form.chegirma_foiz} onChange={e => setForm({ ...form, chegirma_foiz: Number(e.target.value) })} /><Select label="Holat" value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option value="tolangan">To‘langan</option><option value="qisman">Qisman to‘langan</option><option value="qarzdor">Qarzdor</option><option value="imtiyozli">Imtiyozli</option><option value="bekor">Bekor qilingan</option></Select><Input type="date" label="Boshlanish sanasi" required value={form.boshlanish_sana} onChange={e => setForm({ ...form, boshlanish_sana: e.target.value })} /><Input type="date" label="Tugash sanasi" required value={form.tugash_sana} onChange={e => setForm({ ...form, tugash_sana: e.target.value })} /></div><Textarea label="Izoh" rows={3} value={form.izoh} onChange={e => setForm({ ...form, izoh: e.target.value })} /><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setModal(false)}>Bekor qilish</Button><Button type="submit" loading={saving}>Saqlash</Button></div></form></Modal></div>;
}
